ДЗ 1
pandorria/2020-1-Atom-QA-Python-R-Mukhamadeeva pull request #1
Opened 2020-03-01 10:02 UTC by pandorria

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:

В данном домашнем задании были написаны примеры базовых тестов на языке Python на следующие структуры данных:
List
Set
Dictionary
String
Int

На каждую структуру данных было написано по пять тестов, каждый тест содержится в классе с названием TestType, где Type - это имя структуры. В каждом классе один или два теста были параметризованы.

Помимо этого был установлен Python 3.8.1 и pytest.

2020-03-01 10:44 UTC, sniiick requested changes

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +class TestInt:
Предлагаю разделить классы по разным файлам. Так будет более читаемо.

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +        assert x != y
Двойная параметризация здорово, но 2 теста тут упадет, потому что в 2 комбинациях из 4 x и y будут равны. Надо либо поправить параметризацию, либо в тесте поддержать вариант, что числа могут быть и равны

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +    @pytest.mark.parametrize('x', list(range(-5, 7, 2)))
Набор параметров ок, с точки зрения граничных условий я бы еще добавил сюда 0

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +        assert len(x) == 1
Последний параметр пофейлит тест. Так не должно быть. Плюс сточки зрения параметров 1 и 2 эквивалентны. Я бы добавил параметром пустую строку

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +    @pytest.mark.parametrize('x', [[1, 0, 1], [1, 0, 2], [1, 0, 3]])
Я бы здесь несколько изменил тест и превратил бы его в что то подобное:
```python
@pytest.mark.parametrize('x, flag', [([1, 0, 2], True), ([0, 0, 2], False), ([1, 1, 1], True)])
def test_list_4(self, x, flag):
    if flag:
        assert 1 in x
    else:
        assert 1 not in x
```

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +        assert "C", "D1" in x
Плохой ассерт. Питон выполнит `assert "C"`, приведет не пустую строку к bool и получится выполнит `assert True`. А через запятую пишется подробное сообщение об ошибке (`"D1" in x`, что равно `True`)

То есть, меняем "C" на "" и получаем:
```
>       assert '', "D1" in x
E       AssertionError: True
E       assert ''
```

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +        assert x["B"] == 4
То же самое что и выше, с точки зрения параметров проверки эквивалентны. Я бы добавил такой параметр, в котором ключа нет. Ну и поддержал бы это в тесте чтобы он не падал

2020-03-01 10:44 UTC, snicks92 commented on test.py
> +    def test_dict_4(self, x):
Имя тестового метода совпадает с предыдущим

2020-03-01 10:46 UTC, snicks92 commented
Комменты оставил. Из общих пожеланий:
- поместить всю домашнюю работу в отдельную папку, чтобы потом можно было разделять домашки
- разделить тесты на каждую структуру в отдельный файл, чтобы было читаемее
- тесты не должны падать, если тест негативный это нужно поддержать в самом тесте, но сам тест должен быть зелееным

2020-03-01 21:47 UTC, pandorria commented
Замечания исправила

2020-03-03 08:45 UTC, snicks92 commented on test.py
> +class TestInt:
По файоам разделила, но названия теперь не проходят маску пайтеста. Файлы должны начинаться с test_

2020-03-03 11:46 UTC, pandorria commented on test.py
> +class TestInt:
Переименовал файлы

2020-03-03 12:55 UTC, sniiick requested changes
Гораздо лучше, мелкие замечания

2020-03-03 12:55 UTC, snicks92 commented on hw1/test_dict.py
> +        assert "C" and "D1" in x
Теперь сначала проверится "C", то есть bool("C") -> True потом "D1" in x -> True, потом True and True.
Если хочешь проверить 2 ключа то вариантов несколько:

1. В одну строку
```python
assert "C" in x and "D1" in x
```

2. В две строки
```python
assert "C" in x
assert "D1" in x
```

3. Отфильтровать исходный словарь и проверить что он не пустой
```python
filtered =  {k:v for k, v in x.items() if k in ["C", "D1"]}
assert filtered
```

2020-03-03 12:55 UTC, snicks92 commented on hw1/test_int.py
> +    def test_int_4(self, x, y):
Надо поправить название теста, оно совпадает с предыдущим

2020-03-03 14:13 UTC, pandorria commented on hw1/test_int.py
> +    def test_int_4(self, x, y):
Готово

2020-03-03 14:13 UTC, pandorria commented on hw1/test_dict.py
> +        assert "C" and "D1" in x
И тут изменила по первому варианту, на мой взгляд самый простой и читаемый

2020-03-04 18:25 UTC, pandorria commented
Еще раз продублирую, что последние изменения внесла (писала комментарии на Ваши ответы выше)

2020-03-04 19:02 UTC, sniiick approved these changes

2020-03-04 19:02 UTC, merged